channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.0
- pip:
  - mlflow==2.21.3
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - optree==0.15.0
  - pandas==2.0.1
  - torch==2.6.0
  - torchvision==0.21.0
  - tqdm==4.67.1
name: mlflow-env
