name: Benchmark

on:
  push:
    branches:
      - main
    paths:
      - 'advanced_analysis/**'
      - 'tests/performance/**'
      - '.github/workflows/benchmark.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'advanced_analysis/**'
      - 'tests/performance/**'
      - '.github/workflows/benchmark.yml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,all]
          pip install pytest-benchmark

      - name: Run Benchmarks
        run: |
          pytest tests/performance --benchmark-only --benchmark-json=benchmark.json

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
