name: Dependency Scanning

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
      - 'requirements*.txt'
      - '.github/workflows/dependency-scan.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'setup.py'
      - 'requirements*.txt'
      - '.github/workflows/dependency-scan.yml'
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Run Safety Check
        run: |
          safety check -r requirements.txt --full-report

      - name: Run Snyk Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
